export LINUX_TARGET_TRIPLE=x86_64-unknown-linux-gnu
export WIN_MSVC_TARGET_TRIPLE=x86_64-pc-windows-msvc
export WIN_MINGW_TARGET_TRIPLE=x86_64-w64-mingw32
export ARM_BAREMETAL_TARGET_TRIPLE=arm-none-eabi
export RISCV_BAREMETAL_TARGET_TRIPLE=riscv32-unknown-elf

export X86_CORE=X86
export ARM_CORE=ARM
export RISCV_CORE=RISCV
export X86_ARM_RISCV_CORE="X86;ARM;RISCV"

export INSTALLED_CLANG="INSTALLED_CLANG"
export BUILT_CLANG="BUILT_CLANG"
export ARM_GCC="ARM_GCC"
export RISCV_GCC="RISCV_GCC"

PARENT_COMMAND=${BASH_SOURCE[1]}
FILENAME=$(basename "$PARENT_COMMAND")
FILENAME_WO_EXT="_${FILENAME%.*}"

export BUILD_DIR=$(realpath ../build/${FILENAME_WO_EXT}_build)
echo "BUILD_DIR: $BUILD_DIR"